config/routes.rb
Buttr::Application.routes.draw do
  devise_for :users
  root :to => "home#index"
  resources :lists
  resources :list_items
  resources :customers
  resources :shoppers
  resources :users
  get 'notifications/:user_id/customer_dropoff' => 'notifications#customer_dropoff', as: :customer_dropoff
  get 'notifications/:user_id/customer_shopping' => 'notifications#customer_shopping', as: :customer_shopping
  get 'notifications/:user_id/shoppers_shopping' => 'notifications#shoppers_shopping', as: :shoppers_shopping
  get 'customers/:id/wallet' => 'customers#wallet', as: :customer_wallet
  put 'customers/:id/wallet' => 'customers#update_wallet', as: :update_customer_wallet
  put 'shopper/:id/toggle' => 'shoppers#toggle_availability', as: :shopper_toggle_availability
  get 'calendar' => 'shoppers#master_calendar', as: :master_calendar
  get 'admin' => 'home#admin', as: :admin_home
  get 'user/spoof/:new_user_id' => 'users#spoof_user', as: :spoof_user

end

app/models/list.rb
class List
  include Mongoid::Document
  belongs_to :user
  has_many :list_items

  field :shopping_date, type: Time

  def list_items_by_category
    ret = {}
    self.list_items.all.each do |list_item|
      ret[list_item.category.name] = ret[list_item.category.name].nil? ? [list_item] : ret[list_item.category.name] << list_item
    end
    ret
  end

end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_filter :set_list, only: [:show, :update, :destory]
  
  def index
    @lists = List.all
  end

  def new
    @list = List.new
  end

  def create
    @list = List.create(params[:list].permit(:shopping_date, :user_id))
    redirect :show
  end

  def show
  end

  def update
  end

  def destroy
  end

  private
  def set_list
    @list = List.find(params[:id])
  end
end

app/views/lists/_form.html.haml
=form_for @list do |f|
  =f.label :shopping_date
  =f.text_field :shopping_date, class: "datepicker"
  %label
    User
  %span
    =current_user.name
    =f.hidden_field :user_id, value: current_user.id.to_s
  =f.submit "Create"

app/views/lists/index.html.haml
%h2 
  Lists
-@lists.each do |list|
  =link_to list.user.name, list_path(list)

app/views/lists/new.html.haml
%div
  New list
  = render "form"

app/views/lists/show.html.haml
%div
  =@list.shopping_date
  =@list.user.name
  =form_for ListItem.new do |f|
    =f.label :description
    =f.text_field :description
    =f.label :category
    =f.text_field :category
    =f.hidden_field :list_id, value: @list.id
    =f.submit "Add New Item"

  -@list.list_items_by_category.each do |category, list_items|
    %h3
      =category
    -list_items.each do |list_item|
      %div
        %label
          =check_box_tag :active
          =list_item.description