config/routes.rb
Buttr::Application.routes.draw do
  devise_for :users
  root :to => "home#index"
  resources :lists
  resources :list_items
  resources :customers
  resources :shoppers
  resources :users
  get 'notifications/:user_id/customer_dropoff' => 'notifications#customer_dropoff', as: :customer_dropoff
  get 'notifications/:user_id/customer_shopping' => 'notifications#customer_shopping', as: :customer_shopping
  get 'notifications/:user_id/shoppers_shopping' => 'notifications#shoppers_shopping', as: :shoppers_shopping
  get 'customers/:id/wallet' => 'customers#wallet', as: :customer_wallet
  put 'customers/:id/wallet' => 'customers#update_wallet', as: :update_customer_wallet
  put 'shopper/:id/toggle' => 'shoppers#toggle_availability', as: :shopper_toggle_availability
  get 'calendar' => 'shoppers#master_calendar', as: :master_calendar
  get 'admin' => 'home#admin', as: :admin_home
  get 'user/spoof/:new_user_id' => 'users#spoof_user', as: :spoof_user

end

app/models/shopper.rb
class Shopper < User
  has_many :customers
  has_many :shopping_times
  has_many :shopping_availabilities
  has_many :shopping_trips

  field :profile_url, type: String

  def self.shopper_list_for_select
    Shopper.all.map{|shopper| ["#{shopper.first_name} #{shopper.last_name}", shopper.id]}
  end

  class << self
    def master_calendar
      master_calendar = {}
      Shopper.all.each do |shopper|
        shopper_cal = shopper.calendar
        shopper_cal.each do |day, times|
          master_calendar[day] = {} if master_calendar[day].nil?
          times.each do |time, customers|
            master_calendar[day][time] = [] if master_calendar[day][time].nil?
            master_calendar[day][time] += customers
          end
        end
      end
      master_calendar
    end

    def master_availability
      master_availability = {}
      Shopper.all.each do |shopper|
        shopper_avail = shopper.availability
        shopper_avail.each do |day, times|
          master_availability[day] = {} if master_availability[day].nil?
          times.each do |time, customers|
            master_availability[day][time] = [] if master_availability[day][time].nil?
            master_availability[day][time] += [shopper]
          end
        end
      end
      master_availability
    end
  end

  def calendar
    days_hash = {}
    shopping_times.each do |st|
      days_hash[st.day] = {} if days_hash[st.day].nil?
      days_hash[st.day][st.time] = days_hash[st.day][st.time].nil? ? [st] : days_hash[st.day][st.time] + [st]
    end
    days_hash
  end

  def availability
    days_hash = {}
    shopping_availabilities.each do |st|
      days_hash[st.day] = {} if days_hash[st.day].nil?
      days_hash[st.day][st.time] = st
    end
    days_hash
  end

  def update_availability(options)
    day = options[:day]
    time = options[:time]
    zone = options[:zone]
    level = options[:level]
    
    # for some reason find is not returning anything :/
    if availability = shopping_availabilities.find_all{|a| a.day == day && a.time == time}.first
      availability.level = level
      availability.zone = Zone.where(name: zone).first
      availability.save
      return {action: 'update', object: availability}
    else
      availability = shopping_availabilities.create(day: day, time: time, level: level, zone: zone)
      return {action: 'create', object: availability}
    end
  end
end

app/controllers/shoppers_controller.rb
class ShoppersController < UsersController
  before_action :set_shopper, only: [:show, :edit, :update, :toggle_availability]

  def index
    @shoppers = Shopper.all
  end

  def new
    @shopper = Shopper.new
  end

  def edit
  end

  def update
    @shopper.update_attributes(shopper_params)
    redirect_to action: :show
  end

  def show
  end

  def master_calendar
    authorize! :read, :calendar
  end

  def create
    shopper = Shopper.create(shopper_params.merge(password: Devise.friendly_token.first(8)))
    #debugger
    unless shopper.valid?
      flash[:error] = ("Shopper could not be created because: " + format_errors(shopper.errors.full_messages)).html_safe
    end
    redirect_to action: :index
  end

  def toggle_availability
    options = params.slice(:day, :time, :level, :zone)
    status = @shopper.update_availability(options)
    render json: status
  end

  private
  def shopper_params
    params.require(:shopper).permit(:first_name, :last_name, :email, :phone, :profile_url)
  end
  def set_shopper
    @shopper = Shopper.find(params[:id])
  end
end

app/views/shoppers/_calendar.html.haml
-content_for :js_includes do
  = javascript_include_tag "shopper/shopper.js"
%div#loader.hidden
  =image_tag "ajax-loader-circle-ball.gif"
%div.rt
  %table.table.table-bordered.calendar-table
    %thead
      %tr
        %th
        -ShoppingTime.days.each do |day|
          %th
            =day
    -ShoppingTime.times.each do |time|
      %tr
        %td.nopad
          =time.titleize
        -ShoppingTime.days.each do |day|
          -level = !availability[day].nil? && availability[day][time] ? availability[day][time].level : "unavailable"
          -zone = !availability[day].nil? && availability[day][time] && availability[day][time].zone ? availability[day][time].zone.name : nil
          %td{class: "calendar-#{level}"}
            -unless calendar[day].nil?
              -calendar[day][time].nil? ? nil : calendar[day][time].each do |st|
                %div
                  %p
                    - if current_user.is_admin?
                      %div.btn-group
                        %button.btn.btn-xs.btn-default.dropdown-toggle{type:"button", :"data-toggle" => "dropdown"}
                          %span.caret
                        %ul.dropdown-menu{role:"menu"}
                          %li
                            =link_to 'View', customer_path(st.customer)
                          %li
                            =link_to 'Edit', edit_customer_path(st.customer)
                    =st.customer.name
                    -unless shopper
                      ="(#{link_to st.customer.shopper.name, shopper_path(st.customer.shopper)})".html_safe
            -unless shopper
              -if !availability[day].nil? && availability[day][time]
                %p
                  Available:
                  =availability[day][time].map{|s| link_to s.name, shopper_path(s)}.join(', ').html_safe
            -if current_user.is_shopper? && shopper
              =select_tag :"available-#{day}-#{time}", options_for_select(ShoppingAvailability.levels, level), :"data-url" => shopper_toggle_availability_path(id: shopper.id), :"data-day" => day, :"data-time" => time, class: 'js-toggle-available form-control availability'
              =select_tag :"zone-#{day}-#{time}", grouped_options_for_select(Zone.grouped_options, zone), include_blank: true, class: 'js-toggle-available form-control zone'
%style
  @media only screen and (max-width: 768px) {
  td:nth-of-type(2):before { content: "Sunday"; }
  td:nth-of-type(3):before { content: "Monday"; }
  td:nth-of-type(4):before { content: "Tuesday"; }
  td:nth-of-type(5):before { content: "Wednesday"; }
  td:nth-of-type(6):before { content: "Thursday"; }
  td:nth-of-type(7):before { content: "Friday"; }
  td:nth-of-type(8):before { content: "Saturday"; }
  }

app/views/shoppers/_form.html.haml
%div.form-group
  =f.label :first_name
  =f.text_field :first_name, class: 'form-control'
%div.form-group
  =f.label :last_name
  =f.text_field :last_name, class: 'form-control'
%div.form-group
  =f.label :email
  =f.text_field :email, class: 'form-control'
%div.form-group
  =f.label :phone
  =f.text_field :phone, class: 'form-control formatted-phone'
%div.form-group
  =f.label :profile_url
  =f.text_field :profile_url, class: 'form-control'
%div.form-group
  =f.submit "Save", class: 'btn btn-default'

app/views/shoppers/edit.html.haml
=form_for @shopper, url: shopper_path(@shopper), method: :put do |f|
  =render 'form', f: f

app/views/shoppers/index.html.haml
%table.table
  %tr
    %th
      Name
    %th
      Email
    %th
      Phone
    %th
  -if !@shoppers.nil?
    -@shoppers.each do |shopper|
      %tr
        %td
          =link_to shopper.name, shopper_path(shopper)
        %td
          =shopper.email
        %td
          =shopper.phone
        %td
          %div.btn-group
            %button.btn.btn-xs.btn-default.dropdown-toggle{type:"button", :"data-toggle" => "dropdown"}
              Actions
              %span.caret
            %ul.dropdown-menu{role:"menu"}
              %li
                %span{style:"padding:3px 20px;"}
                  Notifcations
              %li.divider
              %li
                =link_to "Shopping", shoppers_shopping_path(user_id: shopper.id)
=link_to "Add Shopper", new_shopper_path

app/views/shoppers/master_calendar.html.haml
%h2
  Master Calendar
= render 'calendar', shopper: nil, calendar: Shopper.master_calendar, availability: Shopper.master_availability

app/views/shoppers/new.html.haml
=form_for @shopper, url: shoppers_path do |f|
  =render 'form', f: f

app/views/shoppers/show.html.haml
%h2
  Shopper
%p
  =@shopper.name
%p
  =@shopper.email
%p
  =@shopper.phone
%p
  =@shopper.profile_url
=link_to "Edit #{@shopper.name}", edit_shopper_path(@shopper)
%h3
  Customers
%ul
  -@shopper.customers.each do |customer|
    %li
      =link_to customer.name, customer_path(customer)
      -shopping_time = customer.shopping_time
      -if shopping_time
        =shopping_time.day
        =shopping_time.time
%h3
  Calendar
= render 'calendar', shopper: @shopper, calendar: @shopper.calendar, availability: @shopper.availability