config/routes.rb
Buttr::Application.routes.draw do
  devise_for :users
  root :to => "home#index"
  resources :lists
  resources :list_items
  resources :customers
  resources :shoppers
  resources :users
  get 'notifications/:user_id/customer_dropoff' => 'notifications#customer_dropoff', as: :customer_dropoff
  get 'notifications/:user_id/customer_shopping' => 'notifications#customer_shopping', as: :customer_shopping
  get 'notifications/:user_id/shoppers_shopping' => 'notifications#shoppers_shopping', as: :shoppers_shopping
  get 'customers/:id/wallet' => 'customers#wallet', as: :customer_wallet
  put 'customers/:id/wallet' => 'customers#update_wallet', as: :update_customer_wallet
  put 'shopper/:id/toggle' => 'shoppers#toggle_availability', as: :shopper_toggle_availability
  get 'calendar' => 'shoppers#master_calendar', as: :master_calendar
  get 'admin' => 'home#admin', as: :admin_home
  get 'user/spoof/:new_user_id' => 'users#spoof_user', as: :spoof_user

end

app/models/customer.rb
class Customer < User
  belongs_to :shopper
  has_one :shopping_time
  has_one :customer_profile
  
  accepts_nested_attributes_for :shopping_time

  # TODO: add geography
  has_many :shopping_trips
  embeds_one :wallet
end

app/controllers/customers_controller.rb
class CustomersController < UsersController
  before_action :set_customer, only: [:show, :wallet, :update_wallet, :edit, :update]
  skip_before_filter :authorized?, only: :wallet

  def index
    @customers = Customer.all
  end

  def new
    @customer = Customer.new
  end

  def show
  end

  def wallet
    authorize! :read, current_user
    @customer.create_wallet if @customer.wallet.nil?
  end

  def update_wallet
    amount = params[:transaction][:amount].to_f
    wallet = @customer.wallet || @customer.create_wallet
    if params[:transaction][:transaction_type] == 'credit'
      wallet.credit(amount, params[:transaction][:note])
    elsif params[:transaction][:transaction_type] == 'debit'
      wallet.debit(amount, params[:transaction][:note])
    end
    wallet.save
    redirect_to action: 'wallet'
  end

  def edit
  end

  def update
    @customer.create_shopping_time(customer_params[:shopping_time_attributes]) unless @customer.shopping_time
    @customer.update_attributes(customer_params)
    redirect_to action: :show
  end

  def create
    @customer = Customer.create(customer_params.merge(password: Devise.friendly_token.first(8)))

    unless @customer.valid?
      flash[:error] = ("Customer could not be created because: " + format_errors(@customer.errors.full_messages)).html_safe
    else
      @customer.shopper = Shopper.find(params[:customer][:shopper_id])
      @customer.save
    end
    redirect_to action: :index
  end

  private
  def customer_params
    params.require(:customer).permit(:first_name, :last_name, :shopper_id, :email, :phone, :wunderlist_url, :feedback_url, shopping_time_attributes: [:id, :shopper_id, :day, :time])
  end

  def set_customer
    @customer = Customer.find(params[:id])
  end
end

app/views/customers/_form.html.haml
-content_for :js_includes do
  = javascript_include_tag "customer/customer.js"
%div.form-group
  =f.label :first_name
  =f.text_field :first_name, class: 'form-control'
%div.form-group
  =f.label :last_name
  =f.text_field :last_name, class: 'form-control'
%div.form-group
  =f.label :shopper_id, "Shopper"
  =f.select :shopper_id, options_for_select(Shopper.shopper_list_for_select), {}, class: 'form-control'
%div.form-group
  =f.label :email
  =f.text_field :email, class: 'form-control'
%div.form-group
  =f.label :phone
  =f.text_field :phone, class: 'form-control formatted-phone'
- @customer.build_shopping_time unless @customer.shopping_time
= f.fields_for :shopping_time do |st|
  =st.hidden_field :shopper_id, value: @customer.shopper_id
  =st.hidden_field :id
  %h4
    Shopping time
  %div{class: "subform"}
    %div.form-group
      =st.label :day
      =st.select :day, options_for_select(ShoppingTime.days, st.object.day), {}, class: 'form-control'
    %div.form-group
      =st.label :time
      =st.select :time, options_for_select(ShoppingTime.times, st.object.time), {}, class: 'form-control'
%div.form-group
  =f.label :wunderlist_url, "Shopping List URL"
  =f.text_field :wunderlist_url, class: 'form-control'
%div.form-group
  =f.label :feedback_url, "Feedback URL"
  =f.text_field :feedback_url, class: 'form-control'
%div.form-group
  =f.submit "Save", class: 'btn btn-default'

app/views/customers/edit.html.haml
=form_for @customer, url: customer_path(@customer), method: :put do |f|
  =render 'form', f: f

app/views/customers/index.html.haml
%table.table
  %tr
    %th
      Name
    %th
      Wallet Balance
    %th
      Shopper
    %th
      Shopping Time
    %th
      Email
    %th
      Phone
    %th
  -if !@customers.nil?
    -@customers.each do |customer|
      %tr
        %td
          =link_to customer.name, customer_path(customer)
        %td
          =link_to number_to_currency(customer.wallet.nil? ? 0 : customer.wallet.balance), customer_wallet_path(customer)
        %td
          -if customer.shopper.present?
            =link_to customer.shopper.name, shopper_path(customer.shopper)
        %td
          -if customer.shopping_time.present?
            =customer.shopping_time.day
            =customer.shopping_time.time
        %td
          =customer.email
        %td
          =customer.phone
        %td
          %div.btn-group
            %button.btn.btn-xs.btn-default.dropdown-toggle{type:"button", :"data-toggle" => "dropdown"}
              Actions
              %span.caret
            %ul.dropdown-menu{role:"menu"}
              %li
                %span{style:"padding:3px 20px;"}
                  Notifcations
              %li.divider
              %li
                =link_to "Shopping", customer_shopping_path(user_id: customer.id)
              %li
                =link_to "Drop off", customer_dropoff_path(user_id: customer.id)
=link_to "Add Customer", new_customer_path

app/views/customers/new.html.haml
=form_for @customer, url: customers_path do |f|
  =render 'form', f: f

app/views/customers/show.html.haml
%h2
  =@customer.name
%p
  =@customer.email
%p
  =@customer.phone
%p
  =link_to "Wallet balance: #{number_to_currency(@customer.wallet.nil? ? 0 : @customer.wallet.balance)}", customer_wallet_path(@customer)
%p
  =@customer.wunderlist_url
%p
  =@customer.feedback_url
%p
  =link_to "Edit", edit_customer_path(@customer)
%h3
  Shopper
%p
  - if @customer.shopper.present?
    =link_to @customer.shopper.name, shopper_path(@customer.shopper)
%p
  -if @customer.shopping_time.present?
    =@customer.shopping_time.day
    =@customer.shopping_time.time

app/views/customers/wallet.html.haml
-content_for :js_includes do
  = javascript_include_tag 'wallet/wallet.js'
%h2
  =@customer.name
%h3
  -balance = @customer.wallet.nil? ? 0 : @customer.wallet.balance
  Wallet balance:
  %span{style: balance < 0 ? 'color:red' : '' }
    #{number_to_currency(balance)}
-if can? :manage, User
  =form_for :transaction, url: update_customer_wallet_path(id: @customer.id), method: :put do |f|
    =f.select :transaction_type, options_for_select([["Credit", "credit"],["Debit","debit"]])
    =f.label :amount, 'Amount $'
    =f.text_field :amount
    =f.label :note
    =f.text_field :note
    =f.submit "Update"

%h2
  Transactions
%table.table
  %tr
    %th
      Date
    %th
      Type
    %th
      Amount
    %th
      Note
  -@customer.wallet.transactions.desc(:created_at).each do |t|
    %tr
      %td
        =t.c_at.in_time_zone.strftime("%B %e, %Y %l:%M:%S %p %Z")
      %td
        =t.transaction_type
      %td
        =number_to_currency(t.amount_cents / 100.0)
      %td
        =t.note