config/routes.rb
Buttr::Application.routes.draw do
  devise_for :users
  root :to => "home#index"
  resources :lists
  resources :list_items
  resources :customers
  resources :shoppers
  resources :users
  get 'notifications/:user_id/customer_dropoff' => 'notifications#customer_dropoff', as: :customer_dropoff
  get 'notifications/:user_id/customer_shopping' => 'notifications#customer_shopping', as: :customer_shopping
  get 'notifications/:user_id/shoppers_shopping' => 'notifications#shoppers_shopping', as: :shoppers_shopping
  get 'customers/:id/wallet' => 'customers#wallet', as: :customer_wallet
  put 'customers/:id/wallet' => 'customers#update_wallet', as: :update_customer_wallet
  put 'shopper/:id/toggle' => 'shoppers#toggle_availability', as: :shopper_toggle_availability
  get 'calendar' => 'shoppers#master_calendar', as: :master_calendar
  get 'admin' => 'home#admin', as: :admin_home
  get 'user/spoof/:new_user_id' => 'users#spoof_user', as: :spoof_user

end

app/views/layouts/_flash.html.erb
<% flash.each do |type, message| %>
  <div class="alert <%= bootstrap_class_for(type) %> fade in">
    <div class="container">
      <button class="close" onclick="$(this).closest('.alert').fadeOut(500,function(){remove()});">×</button>
      <%= message %>
    </div>
  </div>
<% end %>

app/views/layouts/_head.html.haml
%title
  EasyFridge
= csrf_meta_tags
%meta{name:"viewport", content:"width=device-width, user-scalable=no"}
= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true

app/views/layouts/_header.html.haml
%header.nav.navbar.navbar-default.navbar-static-top
  %div.container
    %div.navbar-header
      %a.navbar-brand{href: '/', style: 'padding:5px'}
        =image_tag 'bag icon2.gif', style: 'height:40px;'
        %span#main_logo
          EasyFridge
      %button.navbar-toggle{type:"button", :'data-toggle' => "collapse", :'data-target' => ".navbar-collapse"}
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
    %nav.collapse.navbar-collapse.bs-navbar-collapse{role: "navigation"}
      %ul.nav.navbar-nav
        -case (current_user.nil? ? nil : current_user.user_type)
          -when 'Admin'
            %li
              =link_to "Calendar", master_calendar_path
            %li
              =link_to "Shoppers", shoppers_path
            %li
              =link_to "Customers", customers_path
            %li
              =link_to "Users", users_path
          -when 'Customer'
            %li
              =link_to "My Wallet", customer_wallet_path(current_user)
          -when 'Shopper'
            %li
              =link_to "My Shopper Profile", shopper_path(current_user)
          -else
      %ul.nav.navbar-nav.navbar-right
        - unless current_user
          %li
            = link_to 'Login In', new_user_session_path
          %li
            = link_to 'Sign Up', new_user_registration_path
        - else
          %li.dropdown
            %a.dropdown-toggle{:'data-toggle' => "dropdown"}
              = current_user.name
              %span.caret
            %ul.dropdown-menu
              %li
                = link_to 'Manage my Account', edit_user_registration_path
              %li
                = link_to 'Sign Out', destroy_user_session_path, method: :delete
  = render 'layouts/flash'

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    = render 'layouts/head'
  %body
    = render 'layouts/header'
    %div#main_container.container.content
      = yield
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = yield :js_includes